### PR TITLE
Add attribute to change position of indicators (top|bottom)

### PR DESCRIPTION
**Pull request by jr-k**
Example of usage: 

``` js

<IndicatorViewPager
    indicatorPosition="top"
    style={{flex:1,marginTop:10}}
    indicator={this._renderTitleIndicator()}>
    <View style={{backgroundColor:'cadetblue'}}>
        <Text>page one</Text>
    </View>
    <View style={{backgroundColor:'cornflowerblue'}}>
        <Text>page two</Text>
    </View>
    <View style={{backgroundColor:'#1AA094'}}>
        <Text>page three</Text>
    </View>
</IndicatorViewPager>

```

### CODE REVIEW

**Comment by matto1990** [comment]
It would be very useful if this was merged in. Is there any chance of that?

**Comment by jr-k** [comment]
@matto1990 check here: https://github.com/jr-k/React-Native-ViewPager

**Comment by matto1990** [comment]
Looks good! It's a shame there are two separate libraries, though.

Thanks!

**Comment by jr-k** [comment]
@matto1990 Sure it is, sadly... This pull request has almost 2 months... No choice.

**Comment by zbtang** [comment]
Sorry, but because this feature can be done with prop style of  IndicatorViewPager component, so I didn't merge it. Maybe I should add a prop to make this more convenient, but I am still thinking. Sorry again for no reply this days because of my busy work.

**Comment by matto1990** [comment]
I have ended up implementing it the same way as the title tab example using prop styles, but I think a much cleaner implementation would be to just change the component order as the pull request does.

**Comment by zbtang** [comment]
My implementation is a little outdate, because RN now support `flexDirection: 'column-reverse'`, so you just need to add style `flexDirection: 'column-reverse'` or `flexDirection: 'column'` to make Indicator top or bottom. But both solutions are OK, you can choose one you think better. Thanks!

**Pull request closed without merging**
