### PR TITLE
Replace View.propTypes with ViewPropTypes

### PR DESCRIPTION
**Pull request by rizzomichaelg**
View.propTypes is deprecated. [facebook/react-native@53905a5](https://github.com/facebook/react-native/commit/53905a537a58d028fc5eb1c4e9a8ec967d8cd396)

### CODE REVIEW

**Comment by punksta** [comment]
need this fix

**Comment by ovr** [comment]
ping @zbtang it's realy important fix, because RN works inside dev builds, but crash in production

**Comment by punksta** [comment]
any updates @zbtang

**Comment by zarcode** [comment]
Is this going to be merged soon?

**Comment by bdipak** [comment]
@zbtang could you please confirm when it is going to be merged and released ? It will be really helpful for many of us.

**Comment by parthgandhi7** [comment]
yes please release this update asap.

**Pull request merged**
